config/routes.rb
RackerNews::Application.routes.draw do

  root :to => 'static_pages#main'
  
  post '/users/login' => 'users#login', :as => :login_user
  get '/users/logout' => 'users#logout', :as => :logout_user

  resources :users
  resources :links

  get '/user_links/:short_link' => 'user_links#show', :as => :show_user_link

end

app/models/link.rb
class Link < ActiveRecord::Base
  has_many :user_links
  has_many :users, :through => :user_links
  attr_accessible :url



end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password_hash
  has_many :user_links
  has_many :links, :through => :user_links

  include BCrypt

  def password
    @password ||= Password.new(password_hash)
  end

  def password=(pass)
    @password = Password.create(pass)
    self.password_hash = @password
  end

  def self.create(params={})
    @user = User.new(username: params[:username])
    @user.password = params[:password]
    @user.save!
    @user
  end

  def self.authenticate(params)
    user = User.find_by_username(params[:username])
    (user && user.password == params[:password]) ? user : nil
  end
  
end

app/models/user_link.rb
class UserLink < ActiveRecord::Base
  belongs_to :user
  belongs_to :link
  attr_accessible :clicks, :short_link, :user_id

  def self.create_short_link
    (("A".."Z").to_a + ("z".."z").to_a + (0..9).to_a).sample(6).join
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :require_login

  include ApplicationHelper

  private
    
  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to :root
    end
  end

  def logged_in?
    !!current_user
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  include ApplicationHelper

  def create
    link = Link.find_or_create_by_url(params[:link])
    link.user_links << UserLink.create(:short_link => UserLink.create_short_link, 
                                        :user_id => current_user.id)
    flash[:notice] = link.user_links.last.short_link
    redirect_to :root
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_filter :require_login, :only => [:main]

  def main
    @user = current_user ? current_user : User.new
    @link = Link.new
  end

end

app/controllers/user_links_controller.rb
class UserLinksController < ApplicationController

  def show
    short_link = UserLink.find_by_short_link(params[:short_link])
    url = short_link.link.url
    redirect_to "http://" + url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, :only => [:new, :create, :login]

  def new
    @user = User.new
  end

  def create
    user = User.create(params[:user])
    session[:user_id] = user.id
    redirect_to user
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  def login
    user = User.authenticate(params[:user])
    if user
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:error] = "PROPER CREDENTIALS or GTFO"
      redirect_to :root
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to :root
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    @current_user ||= session[:user_id] &&
      User.find_by_id(session[:user_id])
  end
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RackerNews</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<h2>
  <%= link_to 'Racker News', :root %>  
</h2>
<%= yield %>

</body>
</html>

app/views/static_pages/main.html.erb
<% if @user.username.nil? %>
  <div>
    <h3>Login</h3>
    <%= form_for @user, :url => { :action => "login", :controller=> 'users' } do |f| %>
      <%=  f.text_field :username, :placeholder => 'username' %>
      <%=  f.password_field :password, :placeholder => 'password' %>
      <%= f.submit 'Login' %>
    <% end %>
    <br>
    <%= link_to "create an account", new_user_path %>
  </div>
<% else %>
  <h3>Welcome <%= @user.username %></h3>
  <br>
  <%= link_to "logout", logout_user_path%>

<% end %>
<br>
<%= flash[:error] if flash[:error] %>
<br>

<div>

<%= form_for @link do |f| %>
  <%= f.text_field :url, :placeholder => "Url" %>
  <%= f.submit 'Create Link' %>
<% end %>
<br>
<%= link_to "#{request.url}user_links/" + flash[:notice], 
            show_user_link_path(flash[:notice]) \
            if flash[:notice] %>

</div>

app/views/users/create.html.erb
create.html.erb

app/views/users/new.html.erb
<h1>
  Create a new account
</h1>

<%= form_for @user do |f| %>
  <%= f.text_field :username, :placeholder => 'Username' %>
  <%= f.password_field :password, :placeholder => 'Password' %>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h2><%= @user.username %></h2>